### ISSUE TITLE
DialogWrapper.createRequest(Request) removes top route header incorrectly

### ISSUE THREAD

**Issue by povilasj** [Mobicents/jain-slee.sip#16]
I think DialogWrapper.createRequest(Request) removes top route header incorrectly. It checks if the top header host/port equals to current listening point IP and port and if it match, then it is removed.

This works if route header in the incoming INVITE contains IP address, but if it contains host name (e.g. Route: sip:as.open-ims.test;lr) then the route is not removed which typically result in endless loop because same request gets forwarded again to the AS. It is quite a common case to use host names instead of IP addresses and use DNS based configuration in IMS environments.

Based on SIP strict/loose routing rules I think the top route header could always be removed if it contains "lr" parameter.  Otherwise it should be left as is. If you think this is not safe then it would be a nice to have feature to disable the removal of topmost route header so that this could be consistent and could be done in the service level. 

Patch for proposed solution:
[route-issue.patch.zip](https://github.com/RestComm/jain-slee.sip/files/354509/route-issue.patch.zip)

**Comment by jaimecasero** [comment]
Let me review this scenario, i will come back to you soon. Thanks for reporting and suggestions.

**Comment by deruelle** [comment]
@jaimecasero were you able to review this yet ?

**Comment by deruelle** [comment]
@povilasj can you create a formal pull request as described in our Open Source Playbook https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.vybjjnyzyp0 ? Also can you sign the Contributor license agreement at http://www.telestax.com/open-source/#Contribute so we can accept your contribution ?

**Comment by deruelle** [comment]
@povilasj any news here ?

**Comment by deruelle** [comment]
@povilasj were you able to sign the contributor agreement ?
