### ISSUE TITLE
raActive() doesn't allow to change CACHE_CLASS_NAME

### ISSUE THREAD

**Issue by yarel79** [Mobicents/jain-slee.sip#19]
It is not possible to provide own CACHE_CLASS since RA on raActive() hardcodes specific class name.

In the SipResourceAdaptor.java file you can find block like:
// define impl of the cache  of the HA stack
properties.setProperty(ClusteredSipStack.CACHE_CLASS_NAME_PROPERTY,SipResourceAdaptorMobicentsSipCache.class.getName());`

Reason:
I would like to mock this class on for some unit testing, but current implementation of the RA limits that.

**Comment by yarel79** [comment]
Proposed fix is under: https://github.com/yarel79/jain-slee.sip/commit/22f29de284b3ebb9b803591d1373f440c5af71c4

**Comment by deruelle** [comment]
Thanks @yarel79 

Can you do a pull request as described in our [Open Source Playbook Pull Request Section](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.vybjjnyzyp0https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.vybjjnyzyp0) ? 

Also could you sign our [contributor license agreement](http://www.telestax.com/open-source/#Contribute) so we can accept the contribution and acknowledge you on https://telestax.com/acknowledgements ?

**Comment by deruelle** [comment]
Pull request is at https://github.com/RestComm/jain-slee.sip/pull/22

**Comment by SergeyLee** [comment]
I merged your branch yarel79-issue/19 with adding cacheClassName property to deploy-config.xml and raConfigure(), raActive().
