### ISSUE TITLE
Support for Graceful shutdown feature [SLEE enhancement]

### ISSUE THREAD

**Issue by gfigiel** [Mobicents/jain-slee.sip#20]
Implementation of GracefullyStopableResourceAdaptor interface as to support SLEE feature described here:
https://github.com/RestComm/jain-slee/issues/75

**Comment by gfigiel** [comment]
Hello,
Pull request provided fo rthis feature:
https://github.com/RestComm/jain-slee.sip/pull/21

It fulfilss requirements described and implement in https://github.com/RestComm/jain-slee/issues/75

Best regards,
Greg F.

**Comment by deruelle** [comment]
@SergeyLee were you able to review this PR yet ?

**Comment by gfigiel** [comment]
Sorry Guys for confusion - I requested few days ago to reject my PR as it was not tested well and further testss showed that the implementaiton does not fit the requirements.. Currently we are testing fixed version and it will be puched soon...

**Comment by dblacha** [comment]
Hi @SergeyLee 
I've just pushed final implementation of a Graceful Shutdown.
We are waiting with our PR when the SLEE core will be ready,

Kind Regards,
Dominik.

**Comment by SergeyLee** [comment]
Hi @dblacha 
Sorry for my late answer, I was sick the last 3 days.
So on Friday I almost finish with building JSLEE Release with Graceful shutdown in JSLEE Core.
Now I am finishing it and I need time for adding SS7 RA (CAP) and SIP RA.

Best Regards,
Sergey Lee

**Comment by SergeyLee** [comment]
Hi @dblacha 
I sent to you email with link to new release. Please test it on your side.

**Comment by SergeyLee** [comment]
Hi @dblacha 
Did you test JSLEE Release with Graceful shutdown which I sent to you? Did you test it with SIP RA and SS7/CAP RA?
I was reviewed your code for JSLEE Core and RAs. And now I want to test it locally before I merge you changes to repos.

**Comment by SergeyLee** [comment]
Hi @dblacha 
Did you test JSLEE Release with Graceful shutdown with SIP RA and CAP RA on your side?

**Comment by dblacha** [comment]
Hi @SergeyLee 

Please accept my apologies, unfortunately I couldn't test this release due to some serious issues that happened in our test environment. I'll let you know when our TB become stable and we will continue work with the test,

Kind Regards,
Dominik.

**Comment by satanatoly** [comment]
closing, implemented alternative of graceful shutdown in TelScale version
