### ISSUE TITLE
Make the parameter of port listerning configurable

### ISSUE THREAD

**Issue by vetss** [Mobicents/jain-slee.sip#3]
Now the parameter of SIP RA listerning port is hardcored now. Let's do it easier configurable.

**Comment by SergeyLee** [comment]
Is it enough to configure listening port in SLEE Management Console?
Or you want configure it somewhere else?
I have now error with configuring port in SLEE Management Console:

> java.lang.IllegalArgumentException: Value is of type java.lang.String, required type is java.lang.Integer

and today fix it.

**Comment by SergeyLee** [comment]
See this issue in jain-slee: https://github.com/RestComm/jain-slee/issues/17

**Comment by SergeyLee** [comment]
@vetss Now I am investigating SIP RA and found this code for SIP RA properties (parameters):

[SipResourceAdaptor.raActive](https://github.com/RestComm/jain-slee.sip/blob/master/resources/sip11/ra/src/main/java/org/mobicents/slee/resource/sip11/SipResourceAdaptor.java#L1218-L1226)

Please review this issue with this code.
