### ISSUE TITLE
Allow to specify sipra.properties file location

### ISSUE THREAD

**Issue by yarel79** [Mobicents/jain-slee.sip#32]
At present sipra.properties are loaded the following way:
https://github.com/RestComm/jain-slee.sip/blob/master/resources/sip11/ra/src/main/java/org/mobicents/slee/resource/sip11/SipResourceAdaptor.java#L1219

This is inconvinient, since any change to the file requires extracting sipra.properties from jar, modifying it and then updating jar file.  More over, if multiple sipra.properties are available in a classpath, then the one closer to SipResourceAdaptor class will be chosen. 

As an enhancement, optional RA configuration property should be added which will allow to specify location of the sipra.properties file. If property not specified, then the default file should be chosen.

**Comment by deruelle** [comment]
@yarel79 makes a lot of sense. Would you like to contribute this ?

**Comment by yarel79** [comment]
I'll provide a PR for that.

**Comment by SergeyLee** [comment]
@yarel79 Thanks! I will review it ASAP.

**Comment by yarel79** [comment]
PR has been created - https://github.com/RestComm/jain-slee.sip/pull/33

**Comment by SergeyLee** [comment]
@yarel79 Thanks!
