### ISSUE TITLE
Implement a propagated transaction on DB event error

### ISSUE THREAD

**Issue by croufay** [Mobicents/jain-slee.sip#35]
Your requirement is that not only DB will rollback but also the JSLEE Transaction that executes the event will rollback on DB error

 I want them to work in synergy - as they do when in JTA/JCA.

**Comment by knosach** [comment]
Hi @croufay, rollback implemented. As you can see [here](https://github.com/RestComm/jain-slee.jdbc/blob/d62c75edbfba2bed88c177cbbe8840696635ff38/resources/jdbc/ra/src/main/java/org/restcomm/slee/resource/jdbc/JdbcResourceAdaptor.java#L425) and [here](https://github.com/RestComm/jain-slee.sip/blob/52680a59141eb2e8886b9f72fbef20bbb5a03aa3/examples/sip-jdbc-registrar/sbb/src/main/java/org/mobicents/slee/example/sjr/data/jdbc/UpdateBindingsJdbcTask.java#L218) if we will have some exception we will get rollback transaction
