### ISSUE TITLE
sip jdbc registar error casting

### ISSUE THREAD

**Issue by papamfall** [Mobicents/jain-slee.sip#37]
Hi,
I have this error when i try to reproduce the sip registar jdbc example:

ERROR [SbbEntityImpl] (SLEE-EventRouterExecutor-1-thread-1) Failed to assign and create sbb object java.lang.ClassCastException: org.mobicents.slee.resource.jdbc.JdbcResourceAdaptorSbbInterfaceImpl cannot be cast to org.restcomm.slee.resource.jdbc.JdbcResourceAdaptorSbbInterface

Someone can help me to fix that.

**Comment by SergeyLee** [comment]
Hi @papicool!
What JSLEE release are you using? And from what branch did you reproduce sip registrar jdbc example?
Best regards,
Sergey

**Comment by papamfall** [comment]
i'm using a **restcomm-slee-7.0.63.64-wildfly-10.1.0.Final** and a old release **restcomm-slee-2.8.113.90**
this error come from file master/examples/sip-jdbc-registrar/sbb/src/main/java/org/mobicents/slee/example/sjr/data/jdbc/**DataSourceChildSbb.java**

in this section:
**public void **setSbbContext**(SbbContext arg0)** {
		sbbContextExt = (SbbContextExt) arg0;
		if (tracer == null)
			tracer = sbbContextExt.getTracer(getClass().getSimpleName());
		jdbcRA = (JdbcResourceAdaptorSbbInterface) this.sbbContextExt
				.getResourceAdaptorInterface(jdbcRATypeID, jdbcRALink);
		jdbcACIF = (JdbcActivityContextInterfaceFactory) this.sbbContextExt
				.getActivityContextInterfaceFactory(jdbcRATypeID);
	}

and it's the same when i look for the RA jdbc specification

**Comment by papamfall** [comment]
It's working with my restcomm-slee-7.0.63.64-wildfly-10.1.0.Final now
but not with restcomm-slee-2.8.113.90. I don't know what's the problem

thanks you @SergeyLee

**Comment by SergeyLee** [comment]
@papicool can you check this with last release 2.9
https://github.com/RestComm/jain-slee/releases/tag/2.9.128

**Comment by papamfall** [comment]
@SergeyLee 
It's not working with last release 2.9
I have this error:
[Error.txt](https://github.com/RestComm/jain-slee.sip/files/1072128/Error.txt)
Also when i create a jdbc test SBB with this code :
[testjdbc.txt](https://github.com/RestComm/jain-slee.sip/files/1073956/testjdbc.txt)

**Comment by knosach** [comment]
Hi @papicool if you want to use jain-slee.sip and jain-slee.jdbc  with Jboss please use branch 2.x. This branch uses restcomm package.
